Test collecting the required information from nexus

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,36 +3,6 @@ version: 2.1
 
 orbs:
   ktl-nexus: krakentech/ktl-nexus@4
-# commands:
-# setup:
-#   steps:
-#     - ktl-nexus/login
-#     - run:
-#         name: Create virtualenv
-#         command: |
-#           python -m venv ~/circleci/venv/
-#           echo "source ~/circleci/venv/bin/activate" >> $BASH_ENV
-#           echo "export UV_PROJECT_ENVIRONMENT=~/circleci/venv/" >> $BASH_ENV
-#     - run:
-#         name: Install uv
-#         command: pip install uv
-#     - ktl-nexus/configure_uv
-
-# template-formula:
-#   steps:
-#     - setup
-#     - run: Get tag name from
-#     - run:
-#         name: Wait for package to be published
-#         command: |
-#           for i in {1..10}; do
-#             curl
-#             sleep 20
-#           done
-#     - run:
-#         name: Template formula
-#         command: |
-#           kraken-cli template formula ${{ env.PACKAGE_NAME }}
 jobs:
   test-run:
     executor:
@@ -40,9 +10,28 @@ jobs:
       version: "3.13"
     steps:
       - run:
-          name: DEBUG print the entire pipeline context
+          name: Test for nexus package presence
           command: |
-            echo "Pipeline Git Branch: << pipeline.trigger_parameters.github_app.ref >>"
+            tag="<< pipeline.trigger_parameters.github_app.ref >>"
+            for i in {1..20}; do
+              curl https://nexus.ktl.net/service/rest/v1/search\?repository\=pypi-kraken-private\&name\=kraken-cli | jq --raw-output '.items[] | select(.version=="${tag}") | .assets[] | select(.contentType=="application/x-gzip") | .downloadUrl'
+              if [ $? -eq 0 ]; then
+                break
+              fi
+                echo "Waiting for package to be published..."
+              sleep 30
+            done
+            if [ $? -ne 0 ]; then
+              echo "Package not found after 10 attempts"
+              exit 1
+            fi
+            echo "Package found"
+      - run:
+          name: Template homebrew formula
+          command: |
+            tag="<< pipeline.trigger_parameters.github_app.ref >>"
+            pkg_url=$(curl https://nexus.ktl.net/service/rest/v1/search\?repository\=pypi-kraken-private\&name\=kraken-cli | jq --raw-output '.items[] | select(.version=="${tag}") | .assets[] | select(.contentType=="application/x-gzip") | .downloadUrl')
+            echo "pkg_url: ${pkg_url}"
 workflows:
   test:
     jobs:
